Feature/no01
U-11/mizutaniyu pull request #1
Opened 2020-09-02 11:43 UTC by U-11

##HTML&CSS 課題①NRI模写
###HTMLのコーディングが完了

2020-09-02 12:08 UTC, piasoratech requested changes
コーディング結果をチェックツールなどにかけたでしょうか？
チェックツールにかけたところエラーがまだあるので、セルフチェックをしてからもう一度提出をお願いします！

2020-09-02 14:23 UTC, U-11 commented
HTMLの基本構文チェック、cssの読み込みに関するエラーの解消を行いました。

2020-09-03 10:42 UTC, choimake reviewed
コメントしましたので確認お願いします。

あとSlackでもお伝えしましたが
> ブラウザのコンソールで画像、cssの読み込みに関するエラーも出ていますので、こちらもエラーがゼロになるよう修正してください。
cssは読み込まない、画像ファイルをリポジトリに追加する、という対応で大丈夫です。

こちらの対応もお願いします。
理由は確認のためDevToolsでページをみた際にエラーだらけで、何の不具合が混入しているのか見通しが悪くなるからです。
![スクリーンショット 2020-09-03 19 36 54](https://user-images.githubusercontent.com/52233450/92105061-37738000-ee1d-11ea-9a78-80c5fd2a9098.png)

レビューをするコードというのは基本的に完成品で、これだけ大量のエラーが発生するコードを完成品とは呼びません。

レビューを依頼する際には、完成品を出すという意識を持つようにしてもらえると嬉しいです。

2020-09-03 10:42 UTC, choimake commented on html-nri/index.html
> +    </div><!-- heder-inner -->
コメントにtypo（誤字）がありますので修正してください。
※他にもいくつかあるので合わせて対応お願いします。

2020-09-03 10:42 UTC, choimake commented on html-nri/index.html
> +</div>
header、main、footerの外にdivが実装されていますが、これらのコンテンツはheader、main、footerのどれかの中に入れるべきです。

htmlを文章構造という観点で考えた時、headerはヘッダー、mainは文章本体、footerはフッターを意味します。
そのタグの外に文章を書いてしまうと、それらの文章がヘッダーなのか本体なのか、あるいはフッターなのかがコンピューターから判断できないページとなってしまいます。

divやsectionをheader、main、aside、footerなどの外に単独で実装はせず、header、main、aside、footerの中に実装するようにしましょう。

2020-09-03 10:42 UTC, choimake commented on html-nri/index.html
> +        <li><a href="">株主・投資家情報（IR）</a></li><!-- li:first-child{font-weight:bold;} -->
「#」が抜けています。
※他にもいくつかあるので合わせて修正してください。

2020-09-03 10:42 UTC, choimake commented on html-nri/index.html
> +</html>
ファイルの末尾には改行を入れましょう。

Githubでファイル末尾に改行がないと、赤いマークが出ます。

何故かと言いますと、
「テキストファイルは本来（POSIX的には）必ず最後は改行コードで終わっていなければならない」というルールがあるからです。

それが守られていないときにGithubでは赤いマークという形で警告がでます。

以下、参考URLです。
https://www.cqpub.co.jp/interface/sample/200902/if02_038.pdf

標準規格やIEEE、POSIXなどについて一度確認してみてください。

2020-09-03 10:42 UTC, choimake commented on html-nri/index.html
> +      <p>copyright(c) Nomura Research Institute,Ltd.All rights reserved.</p>
copyrightはsmallタグで実装してください。

2020-09-03 10:48 UTC, choimake commented on html-nri/index.html
> +</div>
補足ですが、以下はOKです。mainをdivで囲んでるだけなので。
```
<div class="red-color">
  <main>
  </main>
</div>
```

これがNGです。mainの外に文章があるので。
```
<div class="red-color">
<p>きゃっほー</p>
</div>
<main>
</main>
```

2020-09-03 13:51 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-09-03 13:51 UTC, choimake commented on html-nri/index.html
> +        <li><a href="#"><small>アクセスマップ</small></a></li>
こちらのリストはsmallタグを適応させる必要はありません。

2020-09-03 13:51 UTC, choimake commented on html-nri/index.html
> +      <p><small>copyright(c) Nomura Research Institute,Ltd.All rights reserved.</small></p>
細かいですがpタグは不要です。

2020-09-03 13:51 UTC, choimake commented on html-nri/index.html
> +  <div class="container header-container">
インデント的にbodyとheaderが同じ深さなのは構造的に変です。
（bodyの一段下にheaderがあるべき）

インデントの深さを全体的に修正してください。エディタのフォーマッタ使うと楽なので是非。

2020-09-05 14:29 UTC, piasoratech requested changes
指摘した以外の部分でも同内容の修正が必要な部分があるので、全体的に再度確認をお願いします。

2020-09-05 14:29 UTC, piasoratech commented on html-nri/index.html
> +      <img src="images/story06_img_01.jpg" alt="ビジネススキー  ム">
altタグ内に不要なスペースがあるので、修正しましょう。

2020-09-05 14:29 UTC, piasoratech commented on html-nri/index.html
> +        <li><a href="#">人材が支えるNRI &gt;</a></li>
`>`や`<`は疑似要素での実装に挑戦してみましょう(CSSで指定するので、HTMLの文章構造に含める必要はありません)

2020-09-05 14:29 UTC, piasoratech commented on html-nri/index.html
> +    <div class="sns-link1">
マジックナンバーを使った命名はやめましょう

2020-09-06 05:51 UTC, gacha1987 reviewed
コメントしましたのでご確認ください

2020-09-06 05:51 UTC, gacha1987 commented on html-nri/index.html
> +          <button><img src="images/glass.svg" alt="検索ボタン "></button>
不要なスペースが残っているみたいです。

2020-09-06 05:51 UTC, gacha1987 commented on html-nri/index.html
> +            <li><a href="#"></a>ニュース</li><!--li:first-child{font-weight:bold;}-->
テキストがaタグ内に入っていません。

2020-09-06 05:51 UTC, gacha1987 commented on html-nri/index.html
> +        <small>copyright(c) Nomura Research Institute,Ltd.All rights reserved.</small>
細かいですが課題のサイトを見ると `Copyright` になっています。

2020-09-06 05:51 UTC, gacha1987 commented on html-nri/index.html
> +        <h3 class="strong-h3">NRIの強み</h3>
クラス名にHTMLタグを含めるのはやめましょう。
HTMLタグを含めてしまうと別のタグに修正した場合、修正のたびに名前を変えなければならず、CSSの指定もある場合はそちらも修正しないといけないのでかなり手間になります。

2020-09-06 11:20 UTC, choimake approved these changes
対応ありがとうございました。LGTMです。
このPRをマージして、新しくブランチを切る形で次の作業に入ってください。

2020-09-06 11:59 UTC, merged