①HTMLの重複クラス名の修正　②CSSの実装
U-11/mizutaniyu pull request #2
Opened 2020-09-10 14:33 UTC by U-11

2020-09-10 18:53 UTC, choimake reviewed
確認しました。
チェッカーに欠けた際のエラーもなく、インデントも揃っていてgoodです。
またレスポンシブにも対応している点も、意欲的でとても良いと思います。

いくつか元サイトと比べてデザインが崩れている点があるので、こちら確認の上対応お願いします。

- 横幅の大きい画面でみた時に、NRIのロゴとハンバーガーの位置が違います。
![スクリーンショット 2020-09-11 3 43 52](https://user-images.githubusercontent.com/52233450/92785312-4391ab80-f3e2-11ea-849c-b6f607e1d90f.png)
![スクリーンショット 2020-09-11 3 43 45](https://user-images.githubusercontent.com/52233450/92785329-47bdc900-f3e2-11ea-8609-d021217dd360.png)

- 画像の縦幅の大きさ、フォントの種類、大きさなど異なっています。
![スクリーンショット 2020-09-11 3 44 22](https://user-images.githubusercontent.com/52233450/92785508-70de5980-f3e2-11ea-98fd-02bd1fa353b4.png)

- hover時の文字と下線の色が異なっています。
![スクリーンショット 2020-09-11 3 50 21](https://user-images.githubusercontent.com/52233450/92785688-9703f980-f3e2-11ea-92a2-08731e6e419e.png)

- ハンバーガーメニューが大きいです。
![スクリーンショット 2020-09-11 3 50 30](https://user-images.githubusercontent.com/52233450/92785778-a84d0600-f3e2-11ea-84b5-62cfb258df0a.png)

- メニューをクリックしたときに四角の枠が出るので消して欲しいです。
![スクリーンショット 2020-09-11 3 50 39](https://user-images.githubusercontent.com/52233450/92785850-b7cc4f00-f3e2-11ea-84ab-86011fb35816.png)

- 「share」の文字とアイコンの高さがズレています。
![スクリーンショット 2020-09-11 3 50 45](https://user-images.githubusercontent.com/52233450/92785959-d0d50000-f3e2-11ea-96a2-37139aa8ea98.png)

- 四角のマークは元サイトでは画像です。四角マークと文字との間に余白がもっと必要です。
![スクリーンショット 2020-09-11 3 50 49](https://user-images.githubusercontent.com/52233450/92786073-e6e2c080-f3e2-11ea-9aa1-cdd85501e7a4.png)

- PDFのアイコンがありません。
![スクリーンショット 2020-09-11 3 50 57](https://user-images.githubusercontent.com/52233450/92786230-08dc4300-f3e3-11ea-8386-17e56a5e0104.png)

- hover時の挙動が違います。
![スクリーンショット 2020-09-11 3 51 06](https://user-images.githubusercontent.com/52233450/92786332-1d204000-f3e3-11ea-8c47-5b24aab23d0b.png)

- フォントの大きさがちょっと違うのと、アイコンとの縦の中央揃えになっていません。
![スクリーンショット 2020-09-11 3 51 19](https://user-images.githubusercontent.com/52233450/92786386-29a49880-f3e3-11ea-98a8-1299019e1ca9.png)

- 投資家の皆様の下とfooterが線で区切られていません。
- 免責事項などのメニューと縦線の色が濃いです。
- Copyrightのフォントのサイズが大きいです。
![スクリーンショット 2020-09-11 3 51 33](https://user-images.githubusercontent.com/52233450/92786571-50fb6580-f3e3-11ea-88c2-876e45eb9f51.png)

2020-09-11 17:29 UTC, U-11 commented
①NRIのロゴとパンくずリスト位置の修正（併せてHTMLにdivの追加）
②keyvisual画像の縦幅の大きさ、フォントの種類、大きさの修正
③ヘッダーnavのhover時の文字と下線の色の修正
④ハンバーガーメニューの修正及びクリック時のアウトラインをnone。
⑤「share」の文字とアイコンの高さを揃える
⑥四角のマークの画像を変更と余白の追加（位置変更）
⑦PDFのアイコンを実装
⑧hover時の挙動の修正
⑨SNSのフォントの大きさ修正とアイコンとの縦の中央揃えを修正
⑩footer上部に区切り線を実装
⑪免責事項などのメニューと縦線の色の統一
⑫Copyrightのフォントのサイズを縮小

2020-09-12 03:05 UTC, piasoratech requested changes
・NRIのアイコンが潰れてしまっているので、見た目を修正しましょう
![image](https://user-images.githubusercontent.com/57445698/92985628-81302a80-f4ef-11ea-85a9-9f6cdcd0ad21.png)

・文字サイズを調整して本家に合わせましょう
![image](https://user-images.githubusercontent.com/57445698/92985642-97d68180-f4ef-11ea-93a4-50f0b209764f.png)

・hover時の挙動とボタン自体の色が異なるので修正しましょう
![image](https://user-images.githubusercontent.com/57445698/92985651-ac1a7e80-f4ef-11ea-9886-1c517897f7ff.png)

・本家サイトは上段と下段でサイズが違うので修正しましょう
![image](https://user-images.githubusercontent.com/57445698/92985668-cc4a3d80-f4ef-11ea-9570-4f7c1982b6a0.png)

・Shareのアイコンと横線の間が本家サイトは空いているので、修正しましょう
![image](https://user-images.githubusercontent.com/57445698/92985681-e3892b00-f4ef-11ea-8cce-5b9859284a3a.png)

・各項目の隙間はこんなに空いていないので、修正しましょう
![image](https://user-images.githubusercontent.com/57445698/92985696-fbf94580-f4ef-11ea-9447-1fd91d1ae210.png)

・ここは「ナレッジ・インサイト」です
![image](https://user-images.githubusercontent.com/57445698/92985709-17645080-f4f0-11ea-9349-4e5dfbfd2cc6.png)

・全体的に左寄せになってしまっています。
![image](https://user-images.githubusercontent.com/57445698/92985714-264b0300-f4f0-11ea-9aca-3fecb9ac0624.png)

2020-09-12 03:05 UTC, piasoratech commented on html-nri/.vscode/settings.json
> +{
vscodeの設定ファイルが含まれてしまっているので、gitignoreに追加してバージョン管理の対象外としてください

2020-09-12 14:26 UTC, U-11 commented
○以下、修正いたしました。
・NRIアイコンの縦横比の修正
・keyvisualの文字サイズを調整
・PDFリンクのhover時の挙動とボタンの色修正
・リンクの上段と下段のサイズ修正
・Shareのアイコンと横線との間の幅を修正
・リンク項目同士の隙間を縮小
・コンテンツの誤字修正「ナレッジ・インサイト」
・リンク全体を中央揃えに変更
・管理対象外ファイルをGitから除外

2020-09-12 14:39 UTC, piasoratech requested changes
おそらく最後の指摘になるかと思います。
画像はimagesフォルダにまとめておきましょう。(統一されていないのが気になります。)
まとめ終わったあとは画像のパスを忘れずに変更してください。

2020-09-12 15:01 UTC, piasoratech approved these changes
OKです！
次に進みましょう

2020-09-12 15:17 UTC, merged